import { IconsSvgModel } from '../models/icons-svg.model';

const pathIcons = '../assets/icons/';
const pathIllustrations = '../assets/illustrations/';

export const ICONS_SVG: IconsSvgModel[] = [
  { name: 'ampm', path: `${pathIcons}ampm.svg` },
  { name: 'avatar', path: `${pathIcons}avatar.svg` },
  { name: 'book', path: `${pathIcons}book.svg` },
  { name: 'calendar', path: `${pathIcons}calendar.svg` },
  { name: 'configuration', path: `${pathIcons}configuration.svg` },
  { name: 'inkafarma', path: `${pathIcons}inkafarma.svg` },
  { name: 'inkafarma-disable', path: `${pathIcons}inkafarma-disable.svg` },
  { name: 'main-logo', path: `${pathIcons}main-logo.svg` },
  { name: 'mifarma', path: `${pathIcons}mifarma.svg` },
  { name: 'mifarma-disable', path: `${pathIcons}mifarma-disable.svg` },
  { name: 'moto', path: `${pathIcons}moto.svg` },
  { name: 'navigation', path: `${pathIcons}navigation.svg` },
  { name: 'stores', path: `${pathIcons}stores.svg` },
  { name: 'store', path: `${pathIcons}store.svg` },
  { name: 'truck', path: `${pathIcons}truck.svg` },
  { name: 'search', path: `${pathIcons}search.svg` },
  { name: 'datepicker', path: `${pathIcons}datepicker.svg` },
  { name: 'ellipse-success', path: `${pathIcons}ellipse-success.svg` },
  { name: 'ellipse-danger', path: `${pathIcons}ellipse-danger.svg` },
  { name: 'ellipse-disabled', path: `${pathIcons}ellipse-disabled.svg` },
  { name: 'credit-card', path: `${pathIcons}credit-card.svg` },
  { name: 'loader', path: `${pathIcons}loader.svg` },
  { name: 'dump', path: `${pathIcons}dump.svg` },
  { name: 'amex', path: `${pathIcons}amex.svg` },
  { name: 'agora', path: `${pathIcons}agora.svg` },
  { name: 'dinners', path: `${pathIcons}dinners.svg` },
  { name: 'mastercard', path: `${pathIcons}mastercard.svg` },
  { name: 'oh', path: `${pathIcons}oh.svg` },
  { name: 'ohVisa', path: `${pathIcons}ohVisa.svg` },
  { name: 'ohMastercard', path: `${pathIcons}ohMastercard.svg` },
  { name: 'visaInterbank', path: `${pathIcons}visaInterbank.svg` },
  { name: 'mastercardInterbank', path: `${pathIcons}mastercardInterbank.svg` },
  { name: 'amexInterbank', path: `${pathIcons}amexInterbank.svg` },
  { name: 'interbank', path: `${pathIcons}interbank.svg` },
  { name: 'visa', path: `${pathIcons}visa.svg` },
  { name: 'logo-brand', path: `${pathIcons}logo.svg` },
  { name: 'done-flow', path: `${pathIcons}done-flow.svg` },
  { name: 'pending-flow', path: `${pathIcons}pending-flow.svg` },
  { name: 'cancel-flow', path: `${pathIcons}cancel-flow.svg` },
  { name: 'cart', path: `${pathIcons}cart.svg` },
  { name: 'info', path: `${pathIcons}info.svg` },
  { name: 'edit-tertiary', path: `${pathIcons}edit-tertiary.svg` },
  { name: 'launch-tertiary', path: `${pathIcons}launch-tertiary.svg` },
  { name: 'launch-tertiary-hover', path: `${pathIcons}launch-tertiary-hover.svg` },
  { name: 'edit-tertiary-hover', path: `${pathIcons}edit-tertiary-hover.svg` },
  { name: 'time-circle', path: `${pathIcons}time-circle.svg` },
  { name: 'crosshair', path: `${pathIcons}crosshair.svg` },
  { name: 'user', path: `${pathIcons}user.svg` },
  { name: 'scooter', path: `${pathIcons}scooter.svg` },
  { name: 'bag', path: `${pathIcons}bag.svg` },
  { name: 'location', path: `${pathIcons}location.svg` },
  { name: 'hourglass', path: `${pathIcons}hourglass.svg` },
  { name: 'money-circle', path: `${pathIcons}money-circle.svg` },
  { name: 'cancel', path: `${pathIcons}cancel.svg` },
  { name: 'done', path: `${pathIcons}done.svg` },
  { name: 'done-white', path: `${pathIcons}done-white.svg` },
  { name: 'orders', path: `${pathIcons}orders.svg` },
  { name: 'home', path: `${pathIcons}home.svg` },
  { name: 'operations', path: `${pathIcons}operations.svg` },
  { name: 'check', path: `${pathIcons}check.svg` },
  {
    name: 'prescription-product',
    path: `${pathIcons}prescription-product.svg`,
  },
  { name: 'product', path: `${pathIcons}product.svg` },
  { name: 'price', path: `${pathIcons}price.svg` },
  { name: 'elipse-error', path: `${pathIcons}elipse-error.svg` },
  { name: 'edit-card', path: `${pathIcons}edit-card.svg` },

  { name: 'logo', path: `${pathIllustrations}logo.svg` },
  { name: 'assigned-orders', path: `${pathIllustrations}assigned-orders.svg` },
  { name: 'call-attention', path: `${pathIllustrations}call-attention.svg` },
  { name: 'communication', path: `${pathIllustrations}communication.svg` },
  { name: 'empty-orders-1', path: `${pathIllustrations}empty-orders-1.svg` },
  { name: 'empty-orders', path: `${pathIllustrations}empty-orders.svg` },
  { name: 'gps', path: `${pathIllustrations}gps.svg` },
  { name: 'login', path: `${pathIllustrations}login.svg` },
  { name: 'look-orders', path: `${pathIllustrations}look-orders.svg` },
  { name: 'looking-files', path: `${pathIllustrations}looking-files.svg` },
  { name: 'lost-connection', path: `${pathIllustrations}lost-connection.svg` },
  {
    name: 'lost-connection-1',
    path: `${pathIllustrations}lost-connection-1.svg`,
  },
  { name: 'on-route', path: `${pathIllustrations}on-route.svg` },
  { name: 'order-canceled', path: `${pathIllustrations}order-canceled.svg` },
  { name: 'order-updated', path: `${pathIllustrations}order-updated.svg` },
  { name: 'payment', path: `${pathIllustrations}payment.svg` },
  { name: 'search-store', path: `${pathIllustrations}search-store.svg` },
  { name: 'send-message', path: `${pathIllustrations}send-message.svg` },
  { name: 'sent', path: `${pathIllustrations}sent.svg` },
  {
    name: 'under-construction',
    path: `${pathIllustrations}under-construction.svg`,
  },
  { name: '404', path: `${pathIllustrations}404.svg` },
  { name: 'responsive', path: `${pathIllustrations}responsive.svg` },
  { name: 'responsive', path: `${pathIllustrations}responsive.svg` },
];
