import { IconsSvgModel } from '../models/icons-svg.model';

const pathIcons = '../assets/icons/';
const pathIllustrations = '../assets/illustrations/';

export const ICONS_SVG: IconsSvgModel[] = [
  {name: 'ampm', path: `${pathIcons}ampm.svg`},
  {name: 'avatar', path: `${pathIcons}avatar.svg`},
  {name: 'book', path: `${pathIcons}book.svg`},
  {name: 'calendar', path: `${pathIcons}calendar.svg`},
  {name: 'configuration', path: `${pathIcons}configuration.svg`},
  {name: 'inkafarma', path: `${pathIcons}inkafarma.svg`},
  {name: 'main-logo', path: `${pathIcons}main-logo.svg`},
  {name: 'mifarma', path: `${pathIcons}mifarma.svg`},
  {name: 'moto', path: `${pathIcons}moto.svg`},
  {name: 'navigation', path: `${pathIcons}navigation.svg`},
  {name: 'stores', path: `${pathIcons}stores.svg`},
  {name: 'truck', path: `${pathIcons}truck.svg`},
  {name: 'search', path: `${pathIcons}search.svg`},
  {name: 'datepicker', path: `${pathIcons}datepicker.svg`},
  {name: 'ellipse-success', path: `${pathIcons}ellipse-success.svg`},
  {name: 'ellipse-disabled', path: `${pathIcons}ellipse-disabled.svg`},
  {name: 'credit-card', path: `${pathIcons}credit-card.svg`},
  {name: 'loader', path: `${pathIcons}loader.svg`},
  {name: 'dump', path: `${pathIcons}dump.svg`},
  {name: 'visa', path: `${pathIcons}visa.svg`},
  {name: 'logo-brand', path: `${pathIcons}logo.svg`},
  {name: 'done-flow', path: `${pathIcons}done-flow.svg`},
  {name: 'pending-flow', path: `${pathIcons}pending-flow.svg`},
  {name: 'cart', path: `${pathIcons}cart.svg`},

  {name: 'logo', path: `${pathIllustrations}logo.svg`},
  {name: 'assigned-orders', path: `${pathIllustrations}assigned-orders.svg`},
  {name: 'call-attention', path: `${pathIllustrations}call-attention.svg`},
  {name: 'communication', path: `${pathIllustrations}communication.svg`},
  {name: 'empty-orders-1', path: `${pathIllustrations}empty-orders-1.svg`},
  {name: 'empty-orders', path: `${pathIllustrations}empty-orders.svg`},
  {name: 'gps', path: `${pathIllustrations}gps.svg`},
  {name: 'login', path: `${pathIllustrations}login.svg`},
  {name: 'look-orders', path: `${pathIllustrations}look-orders.svg`},
  {name: 'looking-files', path: `${pathIllustrations}looking-files.svg`},
  {name: 'lost-connection', path: `${pathIllustrations}lost-connection.svg`},
  {name: 'lost-connection-1', path: `${pathIllustrations}lost-connection-1.svg`},
  {name: 'on-route', path: `${pathIllustrations}on-route.svg`},
  {name: 'order-canceled', path: `${pathIllustrations}order-canceled.svg`},
  {name: 'order-updated', path: `${pathIllustrations}order-updated.svg`},
  {name: 'payment', path: `${pathIllustrations}payment.svg`},
  {name: 'search-store', path: `${pathIllustrations}search-store.svg`},
  {name: 'send-message', path: `${pathIllustrations}send-message.svg`},
  {name: 'sent', path: `${pathIllustrations}sent.svg`},
  {name: 'under-construction', path: `${pathIllustrations}under-construction.svg`},
  {name: '404', path: `${pathIllustrations}404.svg`},
  {name: 'responsive', path: `${pathIllustrations}responsive.svg`},
];
