import { IOrder } from '../interfaces/order.interface';

export const ColumnNameList = {
  orderNumber: 'orderNumber',
  orderId: 'orderId',
  local: 'local',
  channel: 'channel',
  service: 'service',
  promiseDate: 'promiseDate',
  address: 'address',
  status: 'status',
  timeLeft: 'timeLeft',
  actions: 'actions',
};

export enum EOrderStatus {
  entregado = 'ENTREGADO',
  rechazado = 'RECHAZADO',
  enRuta = 'EN RUTA',
  asignado = 'ASIGNADO',
  cancelado = 'CANCELADO',
}

export const OrderDescription = {
  [EOrderStatus.entregado]: 'ENTREGADO',
  [EOrderStatus.rechazado]: 'RECHAZADO',
  [EOrderStatus.enRuta]: 'EN RUTA',
  [EOrderStatus.asignado]: 'ASIGNADO',
  [EOrderStatus.cancelado]: 'CANCELADO',
};

export const OrderStatusColor = {
  [EOrderStatus.entregado]: '#38B57D',
  [EOrderStatus.rechazado]: '#D35530',
  [EOrderStatus.enRuta]: '#6C6FF2',
  [EOrderStatus.asignado]: '#7083AF',
  [EOrderStatus.cancelado]: '#D35530',
};

export const DBOrder: IOrder[] = [
  {
    orderNumber: '1',
    orderId: '1561589012',
    local: 'IKF-061-DOS DE MAYO',
    channel: 'Call Center',
    service: 'AM / PM',
    promiseDate: '30/09/21 10:00 p.m. - 01:00 p.m.',
    address: 'Av. Ejercito, 670 - Miraflores',
    status: 'ENTREGADO',
    timeLeft: '00:00',
  },
  {
    orderNumber: '2',
    orderId: '1561589012',
    local: 'IKF-061-DOS DE MAYO',
    channel: 'Digital',
    service: 'Programado',
    promiseDate: '30/09/21 10:00 p.m. - 01:00 p.m.',
    address: 'Av. Ejercito, 670 - Miraflores',
    status: 'ENTREGADO',
    timeLeft: '00:00',
  },
  {
    orderNumber: '3',
    orderId: '1561589012',
    local: 'IKF-061-DOS DE MAYO',
    channel: 'Call Center',
    service: 'AM / PM',
    promiseDate: '30/09/21 10:00 p.m. - 01:00 p.m.',
    address: 'Av. Ejercito, 670 - Miraflores',
    status: 'ENTREGADO',
    timeLeft: '00:00',
  },
  {
    orderNumber: '4',
    orderId: '1561589012',
    local: 'IKF-061-DOS DE MAYO',
    channel: 'Call Center',
    service: 'AM / PM',
    promiseDate: '30/09/21 10:00 p.m. - 01:00 p.m.',
    address: 'Av. Ejercito, 670 - Miraflores',
    status: 'RECHAZADO',
    timeLeft: '00:00',
  },
  {
    orderNumber: '5',
    orderId: '1561589012',
    local: 'IKF-061-DOS DE MAYO',
    channel: 'Call Center',
    service: 'Express',
    promiseDate: '30/09/21 10:00 p.m. - 01:00 p.m.',
    address: 'Av. Ejercito, 670 - Miraflores',
    status: 'EN RUTA',
    timeLeft: '00:05',
  },
  {
    orderNumber: '6',
    orderId: '1561589012',
    local: 'IKF-061-DOS DE MAYO',
    channel: 'Call Center',
    service: 'Programado',
    promiseDate: '30/09/21 10:00 p.m. - 01:00 p.m.',
    address: 'Av. Ejercito, 670 - Miraflores',
    status: 'ASIGNADO',
    timeLeft: '00:10',
  },
  {
    orderNumber: '7',
    orderId: '1561589012',
    local: 'IKF-061-DOS DE MAYO',
    channel: 'Call Center',
    service: 'AM / PM',
    promiseDate: '30/09/21 10:00 p.m. - 01:00 p.m.',
    address: 'Av. Ejercito, 670 - Miraflores',
    status: 'ASIGNADO',
    timeLeft: '- 00:20',
  },
  {
    orderNumber: '8',
    orderId: '1561589012',
    local: 'IKF-061-DOS DE MAYO',
    channel: 'Call Center',
    service: 'Programado',
    promiseDate: '30/09/21 10:00 p.m. - 01:00 p.m.',
    address: 'Av. Ejercito, 670 - Miraflores',
    status: 'ASIGNADO',
    timeLeft: '- 00:60',
  },
  {
    orderNumber: '9',
    orderId: '1561589012',
    local: 'IKF-061-DOS DE MAYO',
    channel: 'Call Center',
    service: 'AM / PM',
    promiseDate: '30/09/21 10:00 p.m. - 01:00 p.m.',
    address: 'Av. Ejercito, 670 - Miraflores',
    status: 'ASIGNADO',
    timeLeft: '- 00:30',
  },
  {
    orderNumber: '10',
    orderId: '1561589012',
    local: 'IKF-061-DOS DE MAYO',
    channel: 'Call Center',
    service: 'Programado',
    promiseDate: '30/09/21 10:00 p.m. - 01:00 p.m.',
    address: 'Av. Ejercito, 670 - Miraflores',
    status: 'CANCELADO',
    timeLeft: '- 00:40',
  },
];
