export enum ECards {
  amex = 'American Express',
  amexCredit = 'AMEX crédito',
  dinnersDebitCredit = 'Dinners débito/crédito',
  mastercard = 'Mastercard débito/crédito',
  oh = 'Tarjeta OH!',
  ohMastercard = 'TARJETA OH! Mastercard',
  ohVisa = 'TARJETA OH! Visa',
  visaDebitCredit = 'Visa débito/crédito',
  dinners = 'Dinners',
  agora = 'Agora Visa',
  ohDebitCredit = 'TARJETA OH débito/crédito',
  interbank = 'Interbank',
  mastercardPOS = 'MC POS',
  visaPOS = 'VISA POS',
  visa = 'VISA',
  visaSimple = 'visa',
  cash = 'Efectivo en Soles (S/)',
  marketplace = 'Marketplace',
}

export const CCardNameIllustration = {
  [ECards.amex]: 'amex',
  [ECards.amexCredit]: 'amex',
  [ECards.dinnersDebitCredit]: 'dinners',
  [ECards.mastercard]: 'mastercard',
  [ECards.oh]: 'oh',
  [ECards.ohMastercard]: 'ohMastercard',
  [ECards.ohVisa]: 'ohVisa',
  [ECards.visaDebitCredit]: 'visa',
  [ECards.dinners]: 'dinners',
  [ECards.agora]: 'agora',
  [ECards.ohDebitCredit]: 'oh',
  [ECards.interbank]: 'interbank',
  [ECards.mastercardPOS]: 'mastercard',
  [ECards.visaPOS]: 'visa',
  [ECards.visa]: 'visa',
  [ECards.visaSimple]: 'visa',
  [ECards.cash]: '',
  [ECards.marketplace]: '',
};
