import { ETextColor } from '@models/text/text.model';

export enum EStateOrder {
  errorNotDefined = 'ERROR_NOT_DEFINED',
  successDeliverySend = 'SUCCESS_DELIVERY_SEND',
  errorInsertTracker = 'ERROR_INSERT_TRACKER',
  errorInsertInkaventa = 'ERROR_INSERT_INKAVENTA',
  errorReservedOrder = 'ERROR_RESERVED_ORDER',
  errorPicked = 'ERROR_PICKED',
  errorReadyForPickup = 'ERROR_READY_FOR_PICKUP',
  errorAssigned = 'ERROR_ASSIGNED',
  errorOnRouted = 'ERROR_ON_ROUTED',
  errorArrived = 'ERROR_ARRIVED',
  errorDelivered = 'ERROR_DELIVERED',
  errorCancelled = 'ERROR_CANCELLED',
  cancelledOrder = 'CANCELLED_ORDER',
  deliveredOrder = 'DELIVERED_ORDER',
  readyPickupOrder = 'READY_PICKUP_ORDER',
  releasedOrder = 'RELEASED_ORDER',
  confirmed = 'CONFIRMED',
  confirmedTracker = 'CONFIRMED_TRACKER',
  assigned = 'ASSIGNED',
  pickedOrder = 'PICKED_ORDER',
  preparedOrder = 'PREPARED_ORDER',
  onRoutedOrder = 'ON_ROUTED_ORDER',
  arrivedOrder = 'ARRIVED_ORDER',
  checkoutOrder = 'CHECKOUT_ORDER',
  cancelledOrderNotEnoughStock = 'CANCELLED_ORDER_NOT_ENOUGH_STOCK',
  cancelledOrderOnlinePayment = 'CANCELLED_ORDER_ONLINE_PAYMENT',
  cancelledOrderOnlinePaymentNotEnoughStock = 'CANCELLED_ORDER_ONLINE_PAYMENT_NOT_ENOUGH_STOCK',
  rejectedOrder = 'REJECTED_ORDER',
  rejectedOrderOnlinePayment = 'REJECTED_ORDER_ONLINE_PAYMENT',
  errorUpdate = 'ERROR_UPDATE',
  invoiced = 'INVOICED',
  errorInvoiced = 'ERROR_INVOICED',
  errorCheckout = 'ERROR_CHECKOUT',
  partialUpdateOrder = 'PARTIAL_UPDATE_ORDER',
  errorPartialUpdate = 'ERROR_PARTIAL_UPDATE'
}

export const CStateOrderName = {
  [EStateOrder.errorNotDefined]: 'Error no definido',
  [EStateOrder.successDeliverySend]: 'Proceso fulfillment completo satisfactoriamente',
  [EStateOrder.errorInsertTracker]: 'Error al insertar al inkatracker lite',
  [EStateOrder.errorInsertInkaventa]: 'Error al insertar al inkaventa',
  [EStateOrder.errorReservedOrder]: 'Error al reservar una orden',
  [EStateOrder.errorPicked]: 'Error al liberar una orden',
  [EStateOrder.errorReadyForPickup]: 'Error al actualizar el identificador de insink al enviarlo al tracker',
  [EStateOrder.errorAssigned]: 'Error al cambisar de estado a ON_STORE',
  [EStateOrder.errorOnRouted]: 'Error al cambiar de estado al asignar una orden',
  [EStateOrder.errorArrived]: 'Error al cambiar el estado a preparado',
  [EStateOrder.errorDelivered]: 'Error al cambiar el estado en ruta',
  [EStateOrder.errorCancelled]: 'Orden reservada satisfactoriamente',
  [EStateOrder.cancelledOrder]: 'Cancelar una orden',
  [EStateOrder.deliveredOrder]: 'Orden entregada',
  [EStateOrder.readyPickupOrder]: 'Listo para recoger',
  [EStateOrder.releasedOrder]: 'Orden Liberada',
  [EStateOrder.confirmed]: 'Orden que ha sido confirmada satisfactoriamente por el ecommerce',
  [EStateOrder.confirmedTracker]: 'Orden en tienda',
  [EStateOrder.assigned]: 'Orden ya asignada',
  [EStateOrder.pickedOrder]: 'Orden ya preparada',
  [EStateOrder.preparedOrder]: 'Orden que se encuentra en ruta',
  [EStateOrder.onRoutedOrder]: 'Motorizado que ya llegó al destino',
  [EStateOrder.arrivedOrder]: 'Orden rechazada por el motorizado',
  [EStateOrder.checkoutOrder]: 'Orden que ha sido actualiza a checkout correctamente',
  [EStateOrder.cancelledOrderNotEnoughStock]: 'Error al actualizar el estado de arrive de la orden',
  [EStateOrder.cancelledOrderOnlinePayment]: 'Orden cancelada con método de pago en línea',
  [EStateOrder.cancelledOrderOnlinePaymentNotEnoughStock]: 'Error al cancelar una orden',
  [EStateOrder.rejectedOrder]: 'Error al entregar una orden',
  [EStateOrder.rejectedOrderOnlinePayment]: 'Error recoger una orden',
  [EStateOrder.errorUpdate]: 'Error al actualizar una orden',
  [EStateOrder.invoiced]: 'Orden facturada',
  [EStateOrder.errorInvoiced]: 'Error al facturar',
  [EStateOrder.errorCheckout]: 'Error al actualizar a checkout una orden',
  [EStateOrder.partialUpdateOrder]: 'Orden que ha sido actualizada parcialmente',
  [EStateOrder.errorPartialUpdate]: 'Error al actualizar una orden parcial'
};

export const CStateOrderColor = {
  [EStateOrder.errorNotDefined]: ETextColor.error,
  [EStateOrder.successDeliverySend]: ETextColor.success,
  [EStateOrder.errorInsertTracker]: ETextColor.error,
  [EStateOrder.errorInsertInkaventa]: ETextColor.error,
  [EStateOrder.errorReservedOrder]: ETextColor.error,
  [EStateOrder.errorPicked]: ETextColor.error,
  [EStateOrder.errorReadyForPickup]: ETextColor.error,
  [EStateOrder.errorAssigned]: ETextColor.error,
  [EStateOrder.errorOnRouted]: ETextColor.error,
  [EStateOrder.errorArrived]: ETextColor.error,
  [EStateOrder.errorDelivered]: ETextColor.error,
  [EStateOrder.errorCancelled]: ETextColor.error,
  [EStateOrder.cancelledOrder]: ETextColor.error,
  [EStateOrder.deliveredOrder]: ETextColor.error,
  [EStateOrder.readyPickupOrder]: ETextColor.success,
  [EStateOrder.releasedOrder]: ETextColor.success,
  [EStateOrder.confirmed]: ETextColor.success,
  [EStateOrder.confirmedTracker]: ETextColor.success,
  [EStateOrder.assigned]: ETextColor.success,
  [EStateOrder.pickedOrder]: ETextColor.success,
  [EStateOrder.preparedOrder]: ETextColor.error,
  [EStateOrder.onRoutedOrder]: ETextColor.error,
  [EStateOrder.arrivedOrder]: ETextColor.error,
  [EStateOrder.checkoutOrder]: ETextColor.error,
  [EStateOrder.cancelledOrderNotEnoughStock]: ETextColor.warning,
  [EStateOrder.cancelledOrderOnlinePayment]: ETextColor.warning,
  [EStateOrder.cancelledOrderOnlinePaymentNotEnoughStock]: ETextColor.warning,
  [EStateOrder.rejectedOrder]: ETextColor.error,
  [EStateOrder.rejectedOrderOnlinePayment]: ETextColor.error,
  [EStateOrder.errorUpdate]: ETextColor.error,
  [EStateOrder.invoiced]: ETextColor.warning,
  [EStateOrder.errorInvoiced]: ETextColor.error,
  [EStateOrder.errorCheckout]: ETextColor.error,
  [EStateOrder.partialUpdateOrder]: ETextColor.error,
  [EStateOrder.errorPartialUpdate]: ETextColor.error
};
