import { Carrier } from "../models/carrier.model";

export const CarrierListDBDummy: Carrier[] = [
  {
    idCarrier: '1',
    local: 'IKF-061-DOS DE MAYO',
    carrier: 'Renato Fernandez',
    provider: 'CAJE FOREST',
    startHour: '1:02 p.m.',
    state: 'DISPONIBLE',
    paused: 'No',
    isPendingRoute: false,
  } as Carrier,
  {
    idCarrier: '2',
    local: 'IKF-061-DOS DE MAYO',
    carrier: 'Renato Fernandez',
    provider: 'CAJE FOREST',
    startHour: '1:02 p.m.',
    state: 'EN RUTA',
    paused: 'No',
    isPendingRoute: false,
  } as Carrier,
  {
    idCarrier: '3',
    local: 'IKF-061-DOS DE MAYO',
    carrier: 'Renato Fernandez',
    provider: 'CAJE FOREST',
    startHour: '1:02 p.m.',
    state: 'NO DISPONIBLE',
    paused: 'No',
    isPendingRoute: false,
  } as Carrier,
  {
    idCarrier: '4',
    local: 'IKF-061-DOS DE MAYO',
    carrier: 'Renato Fernandez',
    provider: 'CAJE FOREST',
    startHour: '1:02 p.m.',
    state: 'DISPONIBLE',
    paused: 'No',
    isPendingRoute: false,
  } as Carrier,
  {
    idCarrier: '5',
    local: 'IKF-061-DOS DE MAYO',
    carrier: 'Renato Fernandez',
    provider: 'CAJE FOREST',
    startHour: '1:02 p.m.',
    state: 'DISPONIBLE',
    paused: 'No',
    isPendingRoute: false,
  } as Carrier,
  {
    idCarrier: '6',
    local: 'IKF-061-DOS DE MAYO',
    carrier: 'Renato Fernandez',
    provider: 'CAJE FOREST',
    startHour: '1:02 p.m.',
    state: 'DISPONIBLE',
    paused: 'No',
    isPendingRoute: false,
  } as Carrier,
  {
    idCarrier: '7',
    local: 'IKF-061-DOS DE MAYO',
    carrier: 'Renato Fernandez',
    provider: 'CAJE FOREST',
    startHour: '1:02 p.m.',
    state: 'DISPONIBLE',
    paused: 'No',
    isPendingRoute: false,
  } as Carrier,
  {
    idCarrier: '8',
    local: 'IKF-061-DOS DE MAYO',
    carrier: 'Renato Fernandez',
    provider: 'CAJE FOREST',
    startHour: '1:02 p.m.',
    state: 'DISPONIBLE',
    paused: 'No',
    isPendingRoute: false,
  } as Carrier,
  {
    idCarrier: '9',
    local: 'IKF-061-DOS DE MAYO',
    carrier: 'Alejandro Fernandez',
    provider: 'CAJE FOREST',
    startHour: '1:02 p.m.',
    state: 'DISPONIBLE',
    paused: 'No',
    isPendingRoute: false,
  } as Carrier,
  {
    idCarrier: '10',
    local: 'IKF-061-DOS DE MAYO',
    carrier: 'Renato diaz',
    provider: 'CAJE FOREST',
    startHour: '1:02 p.m.',
    state: 'DISPONIBLE',
    paused: 'No',
    isPendingRoute: false,
  } as Carrier,
];
