import { DetailRouteState } from '../interfaces/route.interface';

export const routeState = {
  ['route-checked']: 'detail-route-check',
  ['delivery-checked']: 'detail-route-check',
  ['default']: 'detail-route-default',
};

export const colorRouteTimeline = {
  ['route-checked']: '#6C6FF2',
  ['delivery-checked']: '#6C6FF2',
  ['default']: '#EEF0F5',
};

export const routeDB: DetailRouteState[] = [
  {
    checked: 'route-checked',
    name: 'Asignado',
    realTime: '8:45 a.m.',
    scheduledTime: '9:00 a.m.',
    difference: '-15 min',
  },
  {
    checked: 'route-checked',
    name: 'Traslado al local',
    realTime: '10:00 a.m.',
    scheduledTime: '9:30 a.m.',
    difference: '+30 min',
  },
  {
    checked: 'route-checked',
    name: 'En recojo',
    realTime: '9:55 a.m.',
    scheduledTime: '10:00 a.m.',
    difference: '-5 min',
  },
  {
    checked: 'route-checked',
    name: 'Recibiendo',
    realTime: '10:25 a.m.',
    scheduledTime: '10:30 a.m.',
    difference: '-5 min',
  },
  {
    checked: 'route-checked',
    name: 'Cargando',
    realTime: '10:55 a.m.',
    scheduledTime: '11:00 a.m.',
    difference: '-5 min',
  },
  {
    checked: 'delivery-checked',
    name: 'Entrega 1',
    idDelivery: '8000268563',
    realTimeOnRoute: '11:29 a.m.',
    scheduledTimeOnRoute: '11:30 a.m.',
    differenceOnRoute: '-1 min',
    realTimeOnSite: '-',
    scheduledTimeOnSite: '12:00 a.m.',
    differenceOnSite: '-',
  },
  {
    checked: 'default',
    name: 'Entrega 2',
    idDelivery: '8000268564',
    realTimeOnRoute: '-',
    scheduledTimeOnRoute: '12:00 p.m.',
    differenceOnRoute: null,
    realTimeOnSite: '-',
    scheduledTimeOnSite: '12:30 p.m.',
    differenceOnSite: null,
  },
  {
    checked: 'default',
    name: 'Entrega 3',
    idDelivery: '8000268565',
    realTimeOnRoute: '-',
    scheduledTimeOnRoute: '12:30 p.m.',
    differenceOnRoute: null,
    realTimeOnSite: '-',
    scheduledTimeOnSite: '1:00 p.m.',
    differenceOnSite: null,
  },
  {
    checked: 'default',
    name: 'Entrega 4',
    idDelivery: '8000268566',
    realTimeOnRoute: '-',
    scheduledTimeOnRoute: '1:00 p.m.',
    differenceOnRoute: null,
    realTimeOnSite: '-',
    scheduledTimeOnSite: '1:30 p.m.',
    differenceOnSite: null,
  },
  {
    checked: 'default',
    name: 'Entrega 5',
    idDelivery: '8000268567',
    realTimeOnRoute: '-',
    scheduledTimeOnRoute: '1:30 p.m.',
    differenceOnRoute: null,
    realTimeOnSite: '-',
    scheduledTimeOnSite: '2:00 p.m.',
    differenceOnSite: null,
  },
  {
    checked: 'default',
    name: 'En retorno',
    realTime: null,
    scheduledTime: '2:30 p.m.',
    difference: null,
  },
  {
    checked: 'default',
    name: 'En botica',
    realTime: null,
    scheduledTime: '3:00 p.m.',
    difference: null,
  },
  {
    checked: 'default',
    name: 'Liquidación',
    realTime: null,
    scheduledTime: '3:30 p.m.',
    difference: null,
  },
];
